Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -6,42 +6,136 @@ on:
   pull_request:
     branches:
       - main
+
+      
 jobs:
 
   terraform:
-    # needs: vault
+    name: "Terraform Init"
     runs-on: ubuntu-latest
+    #permissions: 
+      #contents: read
+      #security-events: write
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - name: Checkout
+        uses: actions/checkout@v3
 
       - name: Set up Terraform
-        uses: hashicorp/setup-terraform@v1
+        uses: hashicorp/setup-terraform@v3
+          # terraform_version: 0.13.0:
+
+      - name: Terraform Format
+        id: fmt
+        run: terraform fmt
+
+      - name: Terraform Init
+        id: init
+        run: terraform init
+
+  terraform-validate:
+    name: "Terraform Validate"
+    runs-on: ubuntu-latest
+    needs: terraform  # Optional: make it run after Terraform Init
+
+    steps:
+      - name: Checkout source code
+        uses: actions/checkout@v4
+
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v3
 
       - name: Terraform Init
         run: terraform init
 
-      - name: Terraform Plan
-        run: terraform plan
+      - name: Terraform Validate
+        id: validate
+        run: terraform validate -no-color
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/preview'
-        run: terraform apply -auto-approve
+  tflint:
+    name: "TFLint Scanning"
+    runs-on: ${{ matrix.os }}
 
-  vault:
+    strategy:
+      matrix:
+        os: [ubuntu-latest]
+
+    steps:
+    - uses: actions/checkout@v4
+      name: Checkout source code
+
+    - uses: actions/cache@v4
+      name: Cache plugin dir
+      with:
+        path: ~/.tflint.d/plugins
+        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
+
+    - uses: terraform-linters/setup-tflint@v4
+      name: Setup TFLint
+      with:
+        tflint_version: v0.52.0
+    - name: Show version
+      run: tflint --version
+
+    - name: Init TFLint
+      run: tflint --init
+      env:
+        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
+        GITHUB_TOKEN: ${{ github.token }}
+
+    - name: Run TFLint
+      run: tflint -f compact
+    needs: terraform-validate
+
+  # This workflow contains a single job called "checkov"
+  checkov:
+    name: "Checkov Security Scanning"
+    needs: [tflint]
+    permissions:
+      contents: read # for actions/checkout to fetch code
+      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+
+    # The type of runner that the job will run on
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./vault
 
-    services:
-      vault:
-        image: vault:1.13.3
-        ports:
-          - 8200:8200
-        env:
-          VAULT_DEV_ROOT_TOKEN_ID: root
-          VAULT_DEV_LISTEN_ADDRESS: "http://localhost:8200"
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
+      - uses: actions/checkout@v3
+
+      - name: Checkov GitHub Action
+        uses: bridgecrewio/checkov-action@v12
+        with:
+          # This will add both a CLI output to the console and create a results.sarif file
+          output_format: cli,sarif
+          output_file_path: console,results.sarif
+        
+      - name: Upload SARIF file
+        uses: github/codeql-action/upload-sarif@v3
+        
+        # Results are generated only on a success or failure
+        # this is required since GitHub by default won't run the next step
+        # when the previous one has failed. Security checks that do not pass will 'fail'.
+        # An alternative is to add `continue-on-error: true` to the previous step
+        # Or 'soft_fail: true' to checkov.
+        if: success() || failure()
+        with:
+          sarif_file: results.sarif
+
+  # vault:
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       working-directory: ./vault
+
+  #   services:
+  #     vault:
+  #       image: vault:1.13.3
+  #       ports:
+  #         - 8200:8200
+  #       env:
+  #         VAULT_DEV_ROOT_TOKEN_ID: root
+  #         VAULT_DEV_LISTEN_ADDRESS: "http://localhost:8200"
 
   # terraform:
   #   needs: vault
@@ -63,32 +157,32 @@ jobs:
   #       if: github.ref == 'refs/heads/preview'
   #       run: terraform apply -auto-approve
 
-  tflint:
-    needs: terraform
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+  # tflint:
+  #   needs: terraform
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
 
-      - name: Set up Terraform
-        uses: hashicorp/setup-terraform@v1
+  #     - name: Set up Terraform
+  #       uses: hashicorp/setup-terraform@v1
 
-      - name: Run TFLint
-        run: tflint --init && tflint
+  #     - name: Run TFLint
+  #       run: tflint --init && tflint
 
 
-  checkov:
-    needs: terraform
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+  # checkov:
+  #   needs: terraform
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
 
-      - name: Set up Checkov
-        uses: bridgecrewio/checkov-action@v9.0.0
+  #     - name: Set up Checkov
+  #       uses: bridgecrewio/checkov-action@v9.0.0
 
-      - name: Run Checkov
-        run: checkov -d . --quiet --compact --output json --output-file-path checkov_report.json
+  #     - name: Run Checkov
+  #       run: checkov -d . --quiet --compact --output json --output-file-path checkov_report.json
 
   # Semgrep:
   #   needs: terraform
